#!/bin/python

import math
import os
import random
import re
import sys

# Complete the maxSubsetSum function below.
def max1(a,b):
    if(a>b):
        return a
    else:
        return b
def maxSubsetSum(arr):
    result = []
    for i in range(len(arr)):
        if(i==0):
            result.insert(i,arr[i])
        elif(i==1):
            result.insert(i,max1(arr[i-1],arr[i]))
        else:
            result.insert(i,max1(arr[i],(arr[i]+result[i-2])))
            result[i] = max1(result[i],result[i-1])
    return result[i]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input())

    arr = map(int, raw_input().rstrip().split())

    res = maxSubsetSum(arr)

    fptr.write(str(res) + '\n')

    fptr.close()
