#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'minimumAbsoluteDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def minimumAbsoluteDifference(arr):
    # Write your code here
    arr = sorted(arr)
    print(arr)
    result = []
    for i in range(len(arr)-1):
        r = abs(arr[i] - arr[i+1])
        if(i==0):
            result.append(r)
        else:
            result.append(min(result[i-1], r))
    
    return result[len(result)-1]
    return 1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input().strip())

    arr = map(int, raw_input().rstrip().split())

    result = minimumAbsoluteDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
